# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Francisco de Villalobos
  admin_email: franciscodevillalobos@gmail.com
  admin_password: 22082208
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: <%= ENV["GMAIL_DOMAIN"] =%>
  secret_key_base: aafa907ea32e0430c7bf4837981a2a2f2a898e29befcfd3fa24da52843e614be27686f170ae727316b77d39459aacd4799c7a60762a65b7f2f1ce0e384aec0a9

test:
  domain_name: example.com
  secret_key_base: aafa907ea32e0430c7bf4837981a2a2f2a898e29befcfd3fa24da52843e614be27686f170ae727316b77d39459aacd4799c7a60762a65b7f2f1ce0e384aec0a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: Francisco de Villalobos             # In Heroku to create an environment variable
  admin_email: franciscodevillalobos@gmail.com    # I do heroku config:set ENV_VAR='value'
  admin_password: 22082208
  email_provider_username: franciscodevillalobos #ENV["GMAIL_USERNAME"]
  email_provider_password: ENV["GMAIL_PASSWORD"]
  domain_name: ENV["GMAIL_DOMAIN"]
  secret_key_base: <%= ENV["DEVISE_KEY"] %>       # Always add this two lines exactly like this to deplot to Heroku.
  devise_secret_key: <%= ENV['DEVISE_KEY'] %>
